import os
import json

import faiss
import numpy as np

from ..config import VECTOR_DB_DIR


# ============================================================
# FILE PATHS
# ============================================================

INDEX_PATH = os.path.join(
    VECTOR_DB_DIR,
    "index.faiss"
)

METADATA_PATH = os.path.join(
    VECTOR_DB_DIR,
    "metadata.json"
)


# ============================================================
# CREATE VECTOR DATABASE DIRECTORY
# ============================================================

def create_vector_directory():
    """
    Create the vector database directory
    if it does not already exist.
    """

    os.makedirs(
        VECTOR_DB_DIR,
        exist_ok=True
    )


# ============================================================
# SAVE VECTORS
# ============================================================

def save_vectors(
    chunks: list,
    embeddings
):
    """
    Save document embeddings and metadata
    into FAISS.

    Args:
        chunks:
            List of document chunks with metadata.

        embeddings:
            Embeddings generated by Sentence Transformers.
    """

    if not chunks:

        raise ValueError(
            "Cannot save an empty chunk list."
        )


    if embeddings is None:

        raise ValueError(
            "Embeddings cannot be None."
        )


    if len(chunks) != len(embeddings):

        raise ValueError(
            "Number of chunks and embeddings "
            "must be the same."
        )


    # --------------------------------------------------------
    # Create directory
    # --------------------------------------------------------

    create_vector_directory()


    # --------------------------------------------------------
    # Convert embeddings to NumPy array
    # --------------------------------------------------------

    embeddings = np.asarray(
        embeddings,
        dtype="float32"
    )


    # --------------------------------------------------------
    # Normalize embeddings
    # --------------------------------------------------------

    faiss.normalize_L2(
        embeddings
    )


    # --------------------------------------------------------
    # Create FAISS index
    #
    # IndexFlatIP = Inner Product similarity
    #
    # Because vectors are normalized,
    # Inner Product behaves like cosine similarity.
    # --------------------------------------------------------

    dimension = embeddings.shape[1]

    index = faiss.IndexFlatIP(
        dimension
    )


    # --------------------------------------------------------
    # Add vectors
    # --------------------------------------------------------

    index.add(
        embeddings
    )


    # --------------------------------------------------------
    # Save FAISS index
    # --------------------------------------------------------

    faiss.write_index(
        index,
        INDEX_PATH
    )


    # --------------------------------------------------------
    # Save metadata
    # --------------------------------------------------------

    with open(
        METADATA_PATH,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            chunks,
            file,
            ensure_ascii=False,
            indent=4
        )


    return {
        "vectors": index.ntotal,
        "dimension": dimension,
        "index_path": INDEX_PATH,
        "metadata_path": METADATA_PATH
    }


# ============================================================
# LOAD VECTOR DATABASE
# ============================================================

def load_vectors():
    """
    Load the FAISS index and metadata.

    Returns:
        tuple:
            (index, metadata)
    """

    if not os.path.exists(
        INDEX_PATH
    ):

        raise FileNotFoundError(
            "FAISS index not found. "
            "Upload and process a document first."
        )


    if not os.path.exists(
        METADATA_PATH
    ):

        raise FileNotFoundError(
            "FAISS metadata not found."
        )


    # --------------------------------------------------------
    # Load FAISS index
    # --------------------------------------------------------

    index = faiss.read_index(
        INDEX_PATH
    )


    # --------------------------------------------------------
    # Load metadata
    # --------------------------------------------------------

    with open(
        METADATA_PATH,
        "r",
        encoding="utf-8"
    ) as file:

        metadata = json.load(
            file
        )


    return index, metadata


# ============================================================
# ADD VECTORS TO EXISTING DATABASE
# ============================================================

def add_vectors(
    chunks: list,
    embeddings
):
    """
    Add new document chunks to an existing
    FAISS database.

    If the vector database does not exist,
    a new one is created.
    """

    if not chunks:

        raise ValueError(
            "Cannot add empty chunks."
        )


    if len(chunks) != len(embeddings):

        raise ValueError(
            "Number of chunks and embeddings "
            "must be the same."
        )


    create_vector_directory()


    # --------------------------------------------------------
    # Convert embeddings
    # --------------------------------------------------------

    embeddings = np.asarray(
        embeddings,
        dtype="float32"
    )


    # --------------------------------------------------------
    # Normalize embeddings
    # --------------------------------------------------------

    faiss.normalize_L2(
        embeddings
    )


    # --------------------------------------------------------
    # If index does not exist, create a new one
    # --------------------------------------------------------

    if not os.path.exists(
        INDEX_PATH
    ):

        dimension = embeddings.shape[1]

        index = faiss.IndexFlatIP(
            dimension
        )

        metadata = []


    else:

        # Load existing index
        index = faiss.read_index(
            INDEX_PATH
        )


        # Load existing metadata
        if os.path.exists(
            METADATA_PATH
        ):

            with open(
                METADATA_PATH,
                "r",
                encoding="utf-8"
            ) as file:

                metadata = json.load(
                    file
                )

        else:

            metadata = []


        # Check dimensions
        if embeddings.shape[1] != index.d:

            raise ValueError(
                "Embedding dimension does not match "
                "the existing FAISS index."
            )


    # --------------------------------------------------------
    # Add new vectors
    # --------------------------------------------------------

    index.add(
        embeddings
    )


    # --------------------------------------------------------
    # Add metadata
    # --------------------------------------------------------

    metadata.extend(
        chunks
    )


    # --------------------------------------------------------
    # Save updated index
    # --------------------------------------------------------

    faiss.write_index(
        index,
        INDEX_PATH
    )


    # --------------------------------------------------------
    # Save updated metadata
    # --------------------------------------------------------

    with open(
        METADATA_PATH,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            metadata,
            file,
            ensure_ascii=False,
            indent=4
        )


    return {
        "total_vectors": index.ntotal,
        "total_metadata": len(metadata)
    }


# ============================================================
# DELETE VECTOR DATABASE
# ============================================================

def delete_vector_database():
    """
    Delete the complete FAISS vector database.
    """

    if os.path.exists(
        INDEX_PATH
    ):

        os.remove(
            INDEX_PATH
        )


    if os.path.exists(
        METADATA_PATH
    ):

        os.remove(
            METADATA_PATH
        )


# ============================================================
# CHECK VECTOR DATABASE
# ============================================================

def vector_database_exists():
    """
    Check whether a FAISS vector database exists.
    """

    return (
        os.path.exists(INDEX_PATH)
        and
        os.path.exists(METADATA_PATH)
    )